### ISSUE TITLE
Regressions from Commit 7705869

### ISSUE THREAD

**Issue by WildByDesign** [Lockframe/Firefox-WinUI#12]
The most recent commit https://github.com/Lockframe/Firefox-WinUI/commit/7705869d3c336f29cb35128557a5572c0e2d8a24 made everything even better, however, it introduced two minor bugs:

- ~When Firefox is maximized and using Floating tabs mode, there is a 1-2px space to the right of the Close button where you cannot select the Close button~ FIXED after commit https://github.com/Lockframe/Firefox-WinUI/commit/247f1ddaa904e9577a7109acf2ca9a18814abd67

- The About Firefox dialog is completely blank for anyone not using Mica

**Comment by WildByDesign** [comment]
After commit https://github.com/Lockframe/Firefox-WinUI/commit/247f1ddaa904e9577a7109acf2ca9a18814abd67 the first minor issue is fixed. Thank you.

The commit also mentions `+ Added support for disabled mica in about Firefox pop up`, but unfortunately the About Firefox dialog is still entirely blank on non-Mica. I tried enabling and disabling transparency settings as well in about:config and it was still blank either way.

```css
/* Chrome pages */
@-moz-document url("chrome://browser/content/aboutDialog.xhtml") {
  window#aboutDialog {
	 background-color: transparent !important;
  }
```

```css
/* Chrome pages */
@-moz-document url("chrome://browser/content/aboutDialog.xhtml") {
  window#aboutDialog {
	 background-color: transparent;
  }
```

If I remove the `!important` like above, that fixes it for me. But I am sure that likely breaks it for Mica.

I really appreciate that you are trying to make this theme work for non-Mica users. And I want to thank you for that because your theme does look incredible without Mica.
